import localFont from "next/font/local";
import "./globals.css";

import { Montserrat } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  // weight: [], // Adjust weights as needed
  subsets: ["latin"], // Specify subsets if required
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} overflow-x-hidden antialiased`}>
      <Navbar/> 
      {children}
      <Footer/>
      </body>
    </html>
  );
}
